#!/usr/bin/env python3
"""Build ARTWORK_INDEX.md from what is actually on disk.

Nothing in the index is typed by hand, so it cannot drift from the library the way
a written list would. Run it after adding or retiring any artwork.

    python3 tools/artwork_index.py
"""
import json, os, glob, collections

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
A = os.path.join(ROOT, 'assets')

HEAD = """# ARTWORK INDEX

**Every generation of artwork the film owns, and which of it is currently in the cut.**

Generated by `tools/artwork_index.py`. Do not edit by hand, it will be overwritten.

---

## THE LAW OF THE LIBRARY

**Nothing is ever deleted. It is stored.** A new generation does not kill the one before it. V7 is
not dead and it is not superseded: it is the artwork the film is currently cut from, it sits in
`assets/V7/`, and every frame of it can be referenced, pulled back and used.

**If an old image is better than a new one, modify the old one and use it.** That is the whole point
of keeping them. A rework is not obliged to win. When a v6 is worse than the v4 it replaced, the
right move is to go back to v4 and change the one thing that was wrong with it, not to keep pushing
forward from the worse picture. Going back is not a failure, it is the cheapest thing available:
the old file already exists, already has the right hand and the right paper, and costs nothing.

**The unused alternates below are a reservoir, not waste.** Sixteen V7 frames were made and are not
in the cut. Several of them are the strongest drawings in the library. Before generating anything
new, look here first.

**And the version rule still holds.** Modifying an old image produces a **new number**. Reaching back
to `V7_1_1_runner.jpg` and changing it does not overwrite it; it becomes the next version under the
new frame's name. A published file is never edited in place. See `MANTRA_MANIFEST/modules/versioning.md`.

---
"""


def dims(p):
    try:
        from PIL import Image
        with Image.open(p) as im:
            return '%dx%d' % im.size
    except Exception:
        return '?'


frames = json.load(open(os.path.join(A, 'train', 'frames_v4.json')))
frames = frames['frames'] if isinstance(frames, dict) and 'frames' in frames else frames
used = collections.defaultdict(list)
for f in frames:
    used[f['img']].append(str(f['id']))

out = [HEAD]

# --- the generations
out.append('## THE GENERATIONS\n')
out.append('| folder | images | size | what it is |\n|---|---|---|---|')
WHAT = {
    'V3A': 'early generation', 'V4': 'the big generation, attempts and finals',
    'V5': 'generation five', 'V6': 'generation six',
    'V7': '**the current artwork. All 50 frames of the cut point here**',
    'V8': 'opened 28.8.2026, the scene 1 rebuild lands here',
    'FIXED': 'repaired frames', 'HERO_V3': 'early hero frames',
    'LAYERS': 'background and foreground splits for the animator',
    'REFERENCES': 'character, object and location sheets',
    'live': 'stills pulled from the shoot footage', 'shots': 'shot stills',
    'sb': 'storyboard thumbnails', 'props': 'prop sheets', 'slides': 'slides',
    'reference': 'misc reference',
}
for d in sorted(os.listdir(A)):
    p = os.path.join(A, d)
    if not os.path.isdir(p):
        continue
    imgs = glob.glob(os.path.join(p, '**', '*.jpg'), recursive=True) + \
        glob.glob(os.path.join(p, '**', '*.png'), recursive=True)
    if not imgs:
        continue
    mb = sum(os.path.getsize(x) for x in imgs) / 1024.0 / 1024.0
    out.append('| `%s` | %d | %.0f MB | %s |' % (d, len(imgs), mb, WHAT.get(d, '')))

# --- V7 in detail
v7 = sorted(os.path.basename(p) for p in glob.glob(os.path.join(A, 'V7', '*.jpg')))
inuse = [n for n in v7 if n in used]
spare = [n for n in v7 if n not in used]

out.append('\n---\n\n## V7, IN THE CUT (%d)\n' % len(inuse))
out.append('| file | frames | size |\n|---|---|---|')
for n in inuse:
    out.append('| `%s` | %s | %s |' % (n, ', '.join(used[n]), dims(os.path.join(A, 'V7', n))))

out.append('\n---\n\n## V7, MADE BUT NOT IN THE CUT (%d)\n' % len(spare))
out.append('**Look here before generating anything new.**\n')
out.append('| file | size |\n|---|---|')
for n in spare:
    out.append('| `%s` | %s |' % (n, dims(os.path.join(A, 'V7', n))))

# --- broken links
missing = sorted(set(used) - set(v7))
out.append('\n---\n\n## REFERENCED BY THE FILM BUT NOT ON DISK (%d)\n' % len(missing))
if not missing:
    out.append('None. Every image the cut points at exists.')
else:
    out.append('**`frames_v4.json` points at these and they are nowhere in the repository.**\n')
    out.append('| file | frames |\n|---|---|')
    for n in missing:
        out.append('| `%s` | %s |' % (n, ', '.join(used[n])))

open(os.path.join(ROOT, 'ARTWORK_INDEX.md'), 'w').write('\n'.join(out) + '\n')
print('wrote ARTWORK_INDEX.md: %d in cut, %d spare, %d missing' % (len(inuse), len(spare), len(missing)))
